// @ts-nocheck
/**
 * LLC Designer compatibility engine.
 *
 * This file preserves the validated numerical runtime. One non-mathematical
 * fix moves detail-worker handoff before the initial waveform request.
 * Refactor only after golden operating-point tests.
 */
export {};
(() => {
const $=id=>document.getElementById(id);
const fmt=(x,d=2)=>Number.isFinite(x)?Number(x).toFixed(d):'—';
const clamp=(x,a,b)=>Math.min(Math.max(x,a),b);
const locale=document.querySelector('[data-llc-designer-root]')?.dataset.locale==='zh'?'zh':'en';
const zh=locale==='zh';
const ui=zh?{
  status:{feasible:'可行',marginal:'临界',failed:'失败',numerical:'数值异常'},
  centerRatio:(formula,raw,c)=>`中心匝比 ${formula} = ${fmt(raw,2)}。四舍五入为 ${c}；扫描 +/-2 个匝比步进。`,
  kList:'k 候选列表必须正好包含 9 个值。',
  qList:'Q 候选列表必须正好包含 13 个值。',
  positive:'所有主要规格和候选值都必须为正的有限数。',
  vinOrder:'输入电压必须满足 Vin,min <= Vin,typ <= Vin,max。',
  fsOrder:'最小开关频率比例必须低于最大开关频率比例。',
  loadRange:'最小连续负载必须在 1% 到 100% 之间。',
  calculating:'计算中',
  complete:(count,elapsed)=>`完成：${count} 个候选，用时 ${fmt(elapsed,1)} s`,
  cancelled:'搜索已取消。',
  running:'正在运行设计搜索...',
  progress:(done,total,label)=>`${done}/${total} · ${label}`,
  runPopulate:'运行设计搜索以填充此视图',
  feasibleMarginal:'可行/临界',
  bestMargin:'最佳裕量',
  worstMargin:'最差裕量',
  allReachable:'9 个运行点均可达到，并具有正的最坏工况裕量。',
  tightMargin:'所有运行点均可达到，但至少一个裕量较紧。',
  requiredFs:'所需 fs',
  limit:'限制',
  worstIpk:'最差 Ir,pk',
  worstIrms:'最差 Ir,rms',
  worstVcr:'最差 VCr,pk',
  minComm:'最小换流电流',
  pass:'通过',
  clickEnvelope:'点击计算增益包络以生成图表',
  targetGain:'目标增益范围',
  requiredFsRange:'所需 fs 范围',
  lowMargin:'低频裕量',
  highMargin:'高频裕量',
  tightestCorner:'最紧角点',
  curveNoConverge:'稳态曲线未收敛',
  loadEnvelope:'负载包络',
  load:'负载',
  solvedPoints:'9 个已求解运行点',
  fsAxis:'开关频率 fs [kHz]',
  gainAxis:'ODE 增益 nVo / Vbridge',
  invalidPoint:'该运行点没有有效解',
  noSteady:'该运行点没有有效稳态解。',
  stateCalcFail:'状态平面轨迹计算失败',
  waveCalcFail:'波形计算失败',
  detailFail:'详细计算失败',
  generatingState:'正在生成 ODE 状态平面轨迹...',
  generatingWave:'正在重新积分整周期波形...',
  calcEnvelope:'正在计算轻载、满载和过载下的 ODE 增益包络...',
  recalc:'重新计算细节',
  switchingFrequency:'开关频率',
  commutationCurrent:'换流电流',
  freeInterval:'自由谐振区间',
  stateTransitions:'状态切换',
  discontinuous:'断续整流：检测到自由谐振区间',
  continuous:'连续整流：未观察到明显自由谐振区间',
  longFree:'自由谐振区间较长；请检查轻载环流和控制分支裕量。',
  hasFree:'存在自由谐振区间，状态轨迹已按模式着色。',
  clampStates:'轨迹主要由两个整流钳位状态组成。',
  readPlot:'如何阅读图表',
  readPlotText:'相同增益可能由不同状态组合产生。蓝色和紫色表示整流钳位方向，橙色表示自由谐振，黑色标记表示开关切换。',
  selectEnvelope:'选择设计后点击计算增益包络',
  selectState:'选择设计和运行点以显示状态平面轨迹',
  selectWave:'选择设计和运行点以显示波形',
  runEnvelope:'运行搜索并选择设计后计算此图',
  runState:'运行搜索并选择运行点后计算此图',
  runWave:'运行搜索并选择运行点后计算此图',
  recTable:'运行设计搜索以查看推荐设计。',
  selectedEmpty:'运行设计搜索以选择候选设计。',
  ratioEmpty:'运行设计搜索以比较五个变压器匝比候选的可行区域。'
}:{
  status:{feasible:'Feasible',marginal:'Marginal',failed:'Failed',numerical:'Numerical issue'},
  centerRatio:(formula,raw,c)=>`Center ratio ${formula} = ${fmt(raw,2)}. Rounded to ${c}; scanning +/-2 ratio steps.`,
  kList:'k candidate list must contain exactly 9 values.',
  qList:'Q candidate list must contain exactly 13 values.',
  positive:'All primary specifications and candidate values must be positive.',
  vinOrder:'Input voltage must satisfy Vin,min <= Vin,typ <= Vin,max.',
  fsOrder:'Minimum switching-frequency ratio must be lower than maximum switching-frequency ratio.',
  loadRange:'Minimum continuous load must be between 1% and 100%.',
  calculating:'Calculating',
  complete:(count,elapsed)=>`Complete: ${count} candidates in ${fmt(elapsed,1)} s`,
  cancelled:'Search cancelled.',
  running:'Running design search...',
  progress:(done,total,label)=>`${done}/${total} · ${label}`,
  runPopulate:'Run the design search to populate this view',
  feasibleMarginal:'Feasible/marginal',
  bestMargin:'Best margin',
  worstMargin:'Worst margin',
  allReachable:'All 9 operating points are reachable with positive worst-case margin.',
  tightMargin:'All operating points are reachable, but at least one margin is tight.',
  requiredFs:'Required fs',
  limit:'Limit',
  worstIpk:'Worst Ir,pk',
  worstIrms:'Worst Ir,rms',
  worstVcr:'Worst VCr,pk',
  minComm:'Minimum commutation current',
  pass:'Pass',
  clickEnvelope:'Click Calculate Gain Envelope to generate the gain plot',
  targetGain:'Target gain range',
  requiredFsRange:'Required fs range',
  lowMargin:'Low-frequency margin',
  highMargin:'High-frequency margin',
  tightestCorner:'Tightest corner',
  curveNoConverge:'Steady-state curves did not converge',
  loadEnvelope:'Load envelope',
  load:'load',
  solvedPoints:'9 solved operating points',
  fsAxis:'Switching frequency fs [kHz]',
  gainAxis:'ODE gain nVo / Vbridge',
  invalidPoint:'This operating point has no valid solution',
  noSteady:'This operating point has no valid steady-state solution.',
  stateCalcFail:'State-plane trajectory calculation failed',
  waveCalcFail:'Waveform calculation failed',
  detailFail:'Detail calculation failed',
  generatingState:'Generating the ODE state-plane trajectory...',
  generatingWave:'Reintegrating full-period waveforms...',
  calcEnvelope:'Calculating the ODE gain envelope across light load, full load, and overload...',
  recalc:'Recalculate Details',
  switchingFrequency:'Switching frequency',
  commutationCurrent:'Commutation current',
  freeInterval:'Free interval',
  stateTransitions:'State transitions',
  discontinuous:'Discontinuous rectification: free-resonance interval detected',
  continuous:'Continuous rectification: no significant free interval observed',
  longFree:'The free interval is relatively long; review light-load circulating current and control branch margin.',
  hasFree:'A free interval is present and the state trajectory is colored by mode.',
  clampStates:'The trajectory is mainly composed of the two rectifier-clamp states.',
  readPlot:'How to read the plot',
  readPlotText:'The same gain can be produced by different state combinations. Blue and purple show rectifier-clamp directions, orange shows free resonance, and black markers show switching transitions.',
  selectEnvelope:'Select a design, then click Calculate Gain Envelope',
  selectState:'Select a design and operating point to show the state-plane trajectory',
  selectWave:'Select a design and operating point to show waveforms',
  runEnvelope:'Run the search and select a design to calculate this plot',
  runState:'Run the search and select an operating point to calculate this plot',
  runWave:'Run the search and select an operating point to calculate this plot',
  recTable:'Run the design search to view recommended designs.',
  selectedEmpty:'Run the design search to select a candidate.',
  ratioEmpty:'Run the design search to compare the feasible regions of five transformer-ratio candidates.'
};
const statusLabel=ui.status;
const branchLabelMap=zh?{'Low-frequency boost':'低频升压','High-frequency buck':'高频降压','Near resonance':'近谐振'}:{};
const branchLabel=label=>branchLabelMap[label]||label;
let worker=null,searchWorkers=[],searchState=null,runToken=0,allCandidates=[],selected=null,selectedCornerIndex=0,activeRatio=null,currentConfig=null,detailReq=0,lastWave=null;

let autoNList=[14,15,16,17,18];
function updateFrequencyDisplays(){const f0=+$('f0').value||0,minPct=+$('fsMinRatio').value,maxPct=+$('fsMaxRatio').value;$('fsMinDisplay').textContent=`${minPct}% · ${Math.round(f0*minPct/100)} kHz`;$('fsMaxDisplay').textContent=`${maxPct}% · ${Math.round(f0*maxPct/100)} kHz`}
function updateDerived(){const vo=+$('vo').value,io=+$('io').value;$('power').value=Number.isFinite(vo*io)?fmt(vo*io,1):'';$('roNom').value=io>0?fmt(vo/io,5):'';updateRatios();updateFrequencyDisplays()}
function updateRatios(){const vin=+$('vinTyp').value,vo=+$('vo').value,bridge=$('bridge').value;if(!(vin>0&&vo>0))return;const raw=bridge==='half'?vin/(2*vo):vin/vo,c=Math.max(3,Math.round(raw));autoNList=[c-2,c-1,c,c+1,c+2];autoNList.forEach((n,i)=>$('n'+(i+1)+'Display').textContent=`n = ${n}`);$('ratioFormula').textContent=ui.centerRatio(bridge==='half'?'Vin,typ / (2Vo)':'Vin,typ / Vo',raw,c)}
$('bridge').addEventListener('change',updateDerived);
['vo','io','vinTyp','vinMin','vinMax','f0','fsMinRatio','fsMaxRatio','lightLoad','overload'].forEach(id=>$(id).addEventListener('input',updateDerived));updateDerived();
function parseList(id,count){const arr=$(id).value.split(/[,，\s]+/).filter(Boolean).map(Number).filter(Number.isFinite);if(arr.length!==count)throw new Error(id==='kList'?ui.kList:ui.qList);return arr}
function readConfig(){updateDerived();const f0=+$('f0').value*1e3,minRatio=+$('fsMinRatio').value/100,maxRatio=+$('fsMaxRatio').value/100,cfg={bridge:$('bridge').value,secondary:'fullwave',vinMin:+$('vinMin').value,vinTyp:+$('vinTyp').value,vinMax:+$('vinMax').value,vo:+$('vo').value,io:+$('io').value,light:+$('lightLoad').value/100,overload:1+(+$('overload').value)/100,f0,fsMin:f0*minRatio,fsMax:f0*maxRatio,fsMinRatio:minRatio,fsMaxRatio:maxRatio,iLimit:0,vcrLimit:0,nList:autoNList.slice(),kList:parseList('kList',9),qList:parseList('qList',13)};const nums=[cfg.vinMin,cfg.vinTyp,cfg.vinMax,cfg.vo,cfg.io,cfg.f0,cfg.fsMin,cfg.fsMax,...cfg.nList,...cfg.kList,...cfg.qList];if(nums.some(v=>!Number.isFinite(v)||v<=0))throw new Error(ui.positive);if(!(cfg.vinMin<=cfg.vinTyp&&cfg.vinTyp<=cfg.vinMax))throw new Error(ui.vinOrder);if(cfg.fsMin>=cfg.fsMax)throw new Error(ui.fsOrder);if(!(cfg.light>0&&cfg.light<=1))throw new Error(ui.loadRange);cfg.loads=[cfg.light,1,cfg.overload];cfg.vins=[cfg.vinMin,cfg.vinTyp,cfg.vinMax];return cfg}

function workerMain(){
let cancelled=false;
const clamp=(x,a,b)=>Math.min(Math.max(x,a),b),norm=v=>Math.sqrt(v.reduce((s,x)=>s+x*x,0));
function solveLinear(A,b){const n=b.length,M=A.map((r,i)=>r.slice().concat(b[i]));for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(M[r][c])>Math.abs(M[p][c]))p=r;if(Math.abs(M[p][c])<1e-13)throw new Error('singular');if(p!==c){const t=M[p];M[p]=M[c];M[c]=t}const d=M[c][c];for(let j=c;j<=n;j++)M[c][j]/=d;for(let r=0;r<n;r++){if(r===c)continue;const f=M[r][c];for(let j=c;j<=n;j++)M[r][j]-=f*M[c][j]}}return M.map(r=>r[n])}
function solve2x2(A,b){const [[a,c],[d,e]]=A,det=a*e-c*d;if(Math.abs(det)<1e-15)throw Error('singular2');return[(b[0]*e-c*b[1])/det,(a*b[1]-b[0]*d)/det]}
function solve3x3(A,b){const M=A.map((r,i)=>[...r,b[i]]);for(let c=0;c<3;c++){let p=c;for(let r=c+1;r<3;r++)if(Math.abs(M[r][c])>Math.abs(M[p][c]))p=r;if(Math.abs(M[p][c])<1e-16)throw Error('singular3');[M[c],M[p]]=[M[p],M[c]];const q=M[c][c];for(let j=c;j<4;j++)M[c][j]/=q;for(let r=0;r<3;r++)if(r!==c){const f=M[r][c];for(let j=c;j<4;j++)M[r][j]-=f*M[c][j]}}return M.map(r=>r[3])}
function prop(v0,i0,K,Z,w,t){const th=w*t,c=Math.cos(th),s=Math.sin(th);return{v:K+(v0-K)*c+Z*i0*s,i:i0*c-(v0-K)/Z*s}}
function integralClamped(v0,i0,im0,K,slope,Z,w,t){const th=w*t;return i0*Math.sin(th)/w+((v0-K)/Z)*(Math.cos(th)-1)/w-im0*t-.5*slope*t*t}
function solveAFromSymmetry(s1,s2,Vsym){const map=(v,i)=>{const B=prop(v,i,s1.K,s1.Z,s1.w,s1.t),C=prop(B.v,B.i,s2.K,s2.Z,s2.w,s2.t);return[C.v,C.i]},d=map(0,0),v=map(1,0),i=map(0,1),M=[[v[0]-d[0]+1,i[0]-d[0]],[v[1]-d[1],i[1]-d[1]+1]],bb=[Vsym-d[0],-d[1]],x=solve2x2(M,bb);return{vA:x[0],iA:x[1]}}
function solveInitial3FromSymmetry(segs,Vsym){const map=(vA,iA,imA)=>{let v=vA,i=iA,im=imA;for(const s of segs){const p=prop(v,i,s.K,s.Z,s.w,s.t);v=p.v;i=p.i;if(s.type==='free')im=i;else im+=s.imSlope*s.t}return[v,i,im]},d=map(0,0,0),v=map(1,0,0),i=map(0,1,0),m=map(0,0,1),M=[[v[0]-d[0]+1,i[0]-d[0],m[0]-d[0]],[v[1]-d[1],i[1]-d[1]+1,m[1]-d[1]],[v[2]-d[2],i[2]-d[2],m[2]-d[2]+1]],bb=[Vsym-d[0],-d[1],-d[2]],x=solve3x3(M,bb);return{vA:x[0],iA:x[1],imA:x[2]}}
function cdiv(a,b){const d=b.re*b.re+b.im*b.im;return{re:(a.re*b.re+a.im*b.im)/d,im:(a.im*b.re-a.re*b.im)/d}}
function fha(fn,k,Q){const w=Math.max(1e-6,fn),R=1/Math.max(1e-8,Q),Zs={re:0,im:w-1/w},Zm={re:0,im:w*k},Zp=cdiv({re:0,im:Zm.im*R},{re:R,im:Zm.im}),Zt={re:Zs.re+Zp.re,im:Zs.im+Zp.im},z=cdiv(Zp,Zt);return Math.hypot(z.re,z.im)}
function newtonGeneric(seed,resFn,bounds,quality,scales){let u=seed.slice();u.forEach((v,i)=>u[i]=clamp(v,bounds[i][0],bounds[i][1]));const steps=quality==='curve'?190:quality==='detail'?230:90,maxIt=quality==='curve'?18:quality==='detail'?20:12,tol=quality==='curve'?0.006:quality==='detail'?0.004:0.018;let f=resFn(u,steps),best={n:norm(f),u:u.slice(),it:0};for(let it=0;it<maxIt;it++){if(best.n<tol)break;const J=Array.from({length:4},()=>Array(4).fill(0));for(let j=0;j<4;j++){const h=2e-5*Math.max(scales[j],Math.abs(u[j])),up=u.slice();up[j]=clamp(up[j]+h,bounds[j][0],bounds[j][1]);const fp=resFn(up,steps),dh=up[j]-u[j]||h;for(let i=0;i<4;i++)J[i][j]=(fp[i]-f[i])/dh}let dx;try{dx=solveLinear(J,f.map(v=>-v))}catch(e){break}let ok=false,a=1;for(let ls=0;ls<13;ls++){const un=u.map((v,j)=>clamp(v+a*dx[j],bounds[j][0],bounds[j][1])),fn=resFn(un,steps),nn=norm(fn);if(Number.isFinite(nn)&&nn<norm(f)){u=un;f=fn;ok=true;if(nn<best.n)best={n:nn,u:u.slice(),it:it+1};break}a*=.5}if(!ok)break}return best}
function newton(res,x0,project,maxIt=36){let x=project(x0.slice()),f=res(x),bn=norm(f),best={x:x.slice(),n:bn};if(!Number.isFinite(bn))return null;for(let it=0;it<maxIt&&best.n>3e-7;it++){const n=x.length,J=Array.from({length:n},()=>Array(n).fill(0));for(let j=0;j<n;j++){const h=2e-5*Math.max(1,Math.abs(x[j])),xp=x.slice();xp[j]+=h;const fp=res(project(xp));for(let r=0;r<n;r++)J[r][j]=(fp[r]-f[r])/h}let dx;try{dx=n===2?solve2x2(J,f.map(v=>-v)):solve3x3(J,f.map(v=>-v))}catch{return best.n<3e-4?best:null}let ok=false,a=1;const nf=norm(f);for(let ls=0;ls<14;ls++){const xn=project(x.map((v,j)=>v+a*dx[j])),fn=res(xn),nn=norm(fn);if(Number.isFinite(nn)&&nn<nf){x=xn;f=fn;ok=true;if(nn<best.n)best={x:x.slice(),n:nn};break}a*=.5}if(!ok)break}return best.n<3e-4?best:null}
function trajectoryTank(n,k,Q,cfg){const Rnom=cfg.vo/cfg.io,w0=2*Math.PI*cfg.f0,Rac=8/Math.PI**2*n*n*Rnom,Zr=Q*Rac,Lr=Zr/w0,Cr=1/(w0*Zr),Lm=k*Lr;return{n,k,Q,Rnom,Rac,Zr,Lr,Cr,Lm}}
function solvePoint(tk,cfg,Vin,load,hints=[]){const bridge=cfg.bridge==='half'?'half':'full',vHi=Vin,vLo=bridge==='half'?0:-Vin,vSym=bridge==='half'?Vin:0,D=bridge==='half'?Vin/2:Vin,N=tk.n*cfg.vo,R=tk.Rnom/load,Zr=tk.Zr,wr=1/Math.sqrt(tk.Lr*tk.Cr),Lf=tk.Lr+tk.Lm,Zf=Math.sqrt(Lf/tk.Cr),wf=1/Math.sqrt(Lf*tk.Cr),Iscale=Math.max(1,D/Zr),alpha=tk.Lm/Lf,sMin=Math.PI/cfg.fnMax,sMax=Math.PI/cfg.fnMin,iTol=5e-4*Iscale+2e-4,vTol=3e-4*D+2e-3;
 const target=N/D,qeff=Zr/(8/Math.PI**2*tk.n*tk.n*R);
 if(Math.abs(target-1)<1e-10)return{ok:true,mode:'critical',x:[Math.PI],fn:1,fs:cfg.f0,err:0};
 let est=1,bd=1e99;{const pts=[],roots=[];for(let i=0;i<=180;i++){const f=cfg.fnMin+(cfg.fnMax-cfg.fnMin)*i/180,g=fha(f,tk.k,qeff),e=g-target;pts.push({f,g,e});const desired=(target<.999?f>=.98:target>1.001?f<=1.02:true);const d=Math.abs(e)+(desired?0:10);if(d<bd){bd=d;est=f}if(i){const a=pts[i-1];if(a.e===0)roots.push(a.f);else if(a.e*e<0)roots.push(a.f+(f-a.f)*(-a.e)/(e-a.e))}}const rr=roots.filter(f=>target<.999?f>=.98:target>1.001?f<=1.02:true);if(rr.length){rr.sort((a,b)=>Math.abs(a-1)-Math.abs(b-1));est=rr[0]}}
 const p2=x=>{let a=Math.max(1e-5,x[0]),b=Math.max(1e-5,x[1]),s=a+b;if(s<sMin){const z=sMin/s;a*=z;b*=z}else if(s>sMax){const z=sMax/s;a*=z;b*=z}return[a,b]},p3=x=>{let a=Math.max(1e-5,x[0]),b=Math.max(1e-5,x[1]),c=Math.max(1e-5,x[2]),s=a+b+c;if(s<sMin){const z=sMin/s;a*=z;b*=z;c*=z}else if(s>sMax){const z=sMax/s;a*=z;b*=z;c*=z}return[a,b,c]};
 function case2(x,ret){const[a,b]=x,t1=a/wr,t2=b/wr,Th=t1+t2,s1={K:vHi-N,Z:Zr,w:wr,t:t1},s2={K:vHi,Z:Zf,w:wf,t:t2};let A;try{A=solveAFromSymmetry(s1,s2,vSym)}catch{return ret?null:[1e3,1e3]};const B=prop(A.vA,A.iA,s1.K,s1.Z,s1.w,t1),imB=A.iA+N/tk.Lm*t1,I=integralClamped(A.vA,A.iA,A.iA,s1.K,N/tk.Lm,Zr,wr,t1),Qs=tk.n*I,Ql=(N/tk.n)/R*Th,rr=[(B.i-imB)/Iscale,(Qs-Ql)/Math.max(1e-12,Math.abs(Ql))];if(!ret)return rr;let fm=0;for(let j=0;j<=14;j++){const p=prop(B.v,B.i,s2.K,s2.Z,s2.w,t2*j/14);fm=Math.max(fm,Math.abs(alpha*(vHi-p.v)))}return{mode:'case2',x,fn:Math.PI/(a+b),valid:fm<=N+vTol,res:norm(rr)}}
 function case1(x,ret){const[a,b]=x,t1=a/wr,t2=b/wr,Th=t1+t2,s1={K:vHi-N,Z:Zr,w:wr,t:t1},s2={K:vHi+N,Z:Zr,w:wr,t:t2};let A;try{A=solveAFromSymmetry(s1,s2,vSym)}catch{return ret?null:[1e3,1e3]};const B=prop(A.vA,A.iA,s1.K,s1.Z,s1.w,t1),imA=N*(t2-t1)/(2*tk.Lm),imB=N*Th/(2*tk.Lm),I1=integralClamped(A.vA,A.iA,imA,s1.K,N/tk.Lm,Zr,wr,t1),I2=integralClamped(B.v,B.i,imB,s2.K,-N/tk.Lm,Zr,wr,t2),Qs=tk.n*(I1-I2),Ql=(N/tk.n)/R*Th,rr=[(B.i-imB)/Iscale,(Qs-Ql)/Math.max(1e-12,Math.abs(Ql))],fv=alpha*(vHi-B.v);if(!ret)return rr;return{mode:'case1',x,fn:Math.PI/(a+b),valid:fv<-N+vTol,res:norm(rr)}}
 function over(x,ret){const[a,b]=x,t1=a/wr,t2=b/wr,Th=t1+t2,s1={K:vHi+N,Z:Zr,w:wr,t:t1},s2={K:vHi-N,Z:Zr,w:wr,t:t2};let A;try{A=solveAFromSymmetry(s1,s2,vSym)}catch{return ret?null:[1e3,1e3]};const B=prop(A.vA,A.iA,s1.K,s1.Z,s1.w,t1),imA=N*(t1-t2)/(2*tk.Lm),imB=-N*Th/(2*tk.Lm),I1=integralClamped(A.vA,A.iA,imA,s1.K,-N/tk.Lm,Zr,wr,t1),I2=integralClamped(B.v,B.i,imB,s2.K,N/tk.Lm,Zr,wr,t2),Qs=tk.n*(-I1+I2),Ql=(N/tk.n)/R*Th,rr=[(B.i-imB)/Iscale,(Qs-Ql)/Math.max(1e-12,Math.abs(Ql))];if(!ret)return rr;let ma=-1e99,mb=1e99;for(let j=0;j<=14;j++){let tt=t1*j/14,p=prop(A.vA,A.iA,s1.K,s1.Z,s1.w,tt),im=imA-N/tk.Lm*tt;ma=Math.max(ma,p.i-im)}for(let j=0;j<=14;j++){let tt=t2*j/14,p=prop(B.v,B.i,s2.K,s2.Z,s2.w,tt),im=imB+N/tk.Lm*tt;mb=Math.min(mb,p.i-im)}return{mode:'over',x,fn:Math.PI/(a+b),valid:ma<iTol&&mb>-iTol,res:norm(rr)}}
 function three(x,kind,ret){const[a,b,c]=x,t1=a/wr,t2=b/wr,t3=c/wr,Th=t1+t2+t3;let s1,s2,s3,sign1,sign3,windowSign;if(kind==='under6'){s1={K:vHi-N,Z:Zr,w:wr,t:t1,type:'clamped',imSlope:N/tk.Lm};s2={K:vHi,Z:Zf,w:wf,t:t2,type:'free'};s3={K:vHi+N,Z:Zr,w:wr,t:t3,type:'clamped',imSlope:-N/tk.Lm};sign1=1;sign3=-1;windowSign=-1}else if(kind==='over6'){s1={K:vHi+N,Z:Zr,w:wr,t:t1,type:'clamped',imSlope:-N/tk.Lm};s2={K:vHi,Z:Zf,w:wf,t:t2,type:'free'};s3={K:vHi-N,Z:Zr,w:wr,t:t3,type:'clamped',imSlope:N/tk.Lm};sign1=-1;sign3=1;windowSign=1}else{s1={K:vHi,Z:Zf,w:wf,t:t1,type:'free'};s2={K:vHi-N,Z:Zr,w:wr,t:t2,type:'clamped',imSlope:N/tk.Lm};s3={K:vHi,Z:Zf,w:wf,t:t3,type:'free'};let A;try{A=solveInitial3FromSymmetry([s1,s2,s3],vSym)}catch{return ret?null:[1e3,1e3,1e3]};const B=prop(A.vA,A.iA,s1.K,s1.Z,s1.w,t1),C=prop(B.v,B.i,s2.K,s2.Z,s2.w,t2),imC=B.i+N/tk.Lm*t2,I=integralClamped(B.v,B.i,B.i,s2.K,N/tk.Lm,Zr,wr,t2),Qs=tk.n*I,Ql=(N/tk.n)/R*Th,rr=[(alpha*(vHi-B.v)-N)/D,(C.i-imC)/Iscale,(Qs-Ql)/Math.max(1e-12,Math.abs(Ql))];if(!ret)return rr;let fm1=0,fm3=0,mc=1e99;for(let j=0;j<=12;j++){let tt=t1*j/12,p=prop(A.vA,A.iA,s1.K,s1.Z,s1.w,tt);fm1=Math.max(fm1,Math.abs(alpha*(vHi-p.v)))}for(let j=0;j<=12;j++){let tt=t2*j/12,p=prop(B.v,B.i,s2.K,s2.Z,s2.w,tt),im=B.i+N/tk.Lm*tt;mc=Math.min(mc,p.i-im)}for(let j=0;j<=12;j++){let tt=t3*j/12,p=prop(C.v,C.i,s3.K,s3.Z,s3.w,tt);fm3=Math.max(fm3,Math.abs(alpha*(vHi-p.v)))}return{mode:'FCF',x,fn:Math.PI/(a+b+c),valid:fm1<=N+vTol&&fm3<=N+vTol&&mc>-iTol,res:norm(rr)}}
 let A;try{A=solveInitial3FromSymmetry([s1,s2,s3],vSym)}catch{return ret?null:[1e3,1e3,1e3]};const B=prop(A.vA,A.iA,s1.K,s1.Z,s1.w,t1),imB=A.imA+s1.imSlope*t1,C=prop(B.v,B.i,s2.K,s2.Z,s2.w,t2),I1=integralClamped(A.vA,A.iA,A.imA,s1.K,s1.imSlope,Zr,wr,t1),I3=integralClamped(C.v,C.i,C.i,s3.K,s3.imSlope,Zr,wr,t3),Qs=tk.n*(sign1*I1+sign3*I3),Ql=(N/tk.n)/R*Th,rr=[(B.i-imB)/Iscale,(alpha*(vHi-C.v)-windowSign*N)/D,(Qs-Ql)/Math.max(1e-12,Math.abs(Ql))];if(!ret)return rr;let e1=sign1>0?1e99:-1e99,e3=sign3>0?1e99:-1e99,fm=0;for(let j=0;j<=12;j++){let tt=t1*j/12,p=prop(A.vA,A.iA,s1.K,s1.Z,s1.w,tt),im=A.imA+s1.imSlope*tt,sec=p.i-im;e1=sign1>0?Math.min(e1,sec):Math.max(e1,sec)}for(let j=0;j<=12;j++){let tt=t3*j/12,p=prop(C.v,C.i,s3.K,s3.Z,s3.w,tt),im=C.i+s3.imSlope*tt,sec=p.i-im;e3=sign3>0?Math.min(e3,sec):Math.max(e3,sec)}for(let j=0;j<=12;j++){let tt=t2*j/12,p=prop(B.v,B.i,s2.K,s2.Z,s2.w,tt);fm=Math.max(fm,Math.abs(alpha*(vHi-p.v)))}const ok1=sign1>0?e1>-iTol:e1<iTol,ok3=sign3>0?e3>-iTol:e3<iTol;return{mode:kind,x,fn:Math.PI/(a+b+c),valid:ok1&&ok3&&fm<=N+vTol,res:norm(rr)}}
 const modeFns={case2:{n:2,res:case2},case1:{n:2,res:case1},over:{n:2,res:over},under6:{n:3,res:x=>three(x,'under6',false),ret:x=>three(x,'under6',true)},over6:{n:3,res:x=>three(x,'over6',false),ret:x=>three(x,'over6',true)},FCF:{n:3,res:x=>three(x,'FCF',false),ret:x=>three(x,'FCF',true)}};

 const sideOk=o=>o&&o.valid&&o.fn>=cfg.fnMin-1e-6&&o.fn<=cfg.fnMax+1e-6&&!((target>1.001&&o.fn>1.03)||(target<.999&&o.fn<.97));
 for(let hi=0;hi<Math.min(2,hints.length);hi++){const h=hints[hi],m=h&&modeFns[h.mode];if(!m||!Array.isArray(h.x))continue;const ret=m.ret||((x)=>m.res(x,true)),proj=m.n===2?p2:p3,r=newton(m.res,h.x,proj,20);if(r){const o=ret(r.x);if(sideOk(o))return{ok:true,mode:o.mode,x:o.x,fn:o.fn,fs:o.fn*cfg.f0,err:o.res,target,est,fastHint:true}}}
 const preferred=target<.999?(load<.5?['FCF','over6','over','case2']:load<1.15?['over6','over','FCF','case2']:['over','over6','FCF','case2']):['case2','under6','case1','FCF'];
 const allModes=[...preferred,...Object.keys(modeFns).filter(x=>!preferred.includes(x))],s0=Math.PI/est,sols=[];
 function tryMode(name,seedList,fallback){const m=modeFns[name],ret=m.ret||((x)=>m.res(x,true)),proj=m.n===2?p2:p3;for(const z of seedList){const r=newton(m.res,z,proj,32);if(r){const o=ret(r.x);if(o&&o.valid&&o.fn>=cfg.fnMin-1e-6&&o.fn<=cfg.fnMax+1e-6){sols.push(o);return true}}}if(!fallback)return false;const sums=[s0,Math.PI,clamp(s0*.82,sMin,sMax),clamp(s0*1.18,sMin,sMax)];if(m.n===2){for(const s of sums)for(const f of [.01,.03,.06,.12,.22,.4,.6,.78,.88,.94,.97,.99]){const r=newton(m.res,[s*f,s*(1-f)],proj);if(r){const o=ret(r.x);if(o&&o.valid){sols.push(o);return true}}}}else{const fr=[[.12,.22,.66],[.2,.25,.55],[.3,.25,.45],[.15,.45,.4],[.4,.25,.35],[.55,.25,.2],[.65,.22,.13],[.25,.5,.25]];for(const s of sums)for(const f of fr){const r=newton(m.res,f.map(v=>s*v),proj);if(r){const o=ret(r.x);if(o&&o.valid){sols.push(o);return true}}}}return false}
 for(const name of allModes){const hs=hints.filter(h=>h&&h.mode===name&&Array.isArray(h.x)).map(h=>h.x);tryMode(name,hs,false)}
 if(!sols.length){for(const name of allModes){if(tryMode(name,[],true)&&sols.length>=2)break}}
 if(!sols.length)return{ok:false,target,est,reason:'no valid trajectory mode'};
 sols.sort((a,b)=>{const pa=(target>1.001&&a.fn>1.02)||(target<.999&&a.fn<.98)?1:0,pb=(target>1.001&&b.fn>1.02)||(target<.999&&b.fn<.98)?1:0;return pa-pb||Math.abs(a.fn-est)-Math.abs(b.fn-est)});const z=sols[0];return{ok:true,mode:z.mode,x:z.x,fn:z.fn,fs:z.fn*cfg.f0,err:z.res,target,est};
}
let trajectoryGuideHints=new Map();
function den(pp){return pp.bridge==='half'?pp.Vin/2:pp.Vin}function sym(pp){return pp.bridge==='half'?pp.Vin:0}
function selectMode(x,vs,pp,N){const sec=x[1]-x[2],Lf=pp.Lr+pp.Lm,freeV=pp.Lm/Lf*(vs-x[0]),eps=Math.max(1e-9,2e-8*den(pp)/Math.max(pp.Zr,1e-9));if(sec>eps)return 1;if(sec<-eps)return -1;if(freeV>N+1e-8)return 1;if(freeV<-N-1e-8)return -1;return 0}
function derivMode(x,vs,pp,N,mode){const v=x[0],ir=x[1],im=x[2];if(mode===0){const di=(vs-v)/(pp.Lr+pp.Lm),i=.5*(ir+im);return [i/pp.Cr,di,di]}const vlm=mode*N;return [ir/pp.Cr,(vs-v-vlm)/pp.Lr,vlm/pp.Lm]}
function rk4Mode(x,h,vs,pp,N,mode){const k1=derivMode(x,vs,pp,N,mode),x2=x.map((v,i)=>v+.5*h*k1[i]),k2=derivMode(x2,vs,pp,N,mode),x3=x.map((v,i)=>v+.5*h*k2[i]),k3=derivMode(x3,vs,pp,N,mode),x4=x.map((v,i)=>v+h*k3[i]),k4=derivMode(x4,vs,pp,N,mode);return x.map((v,i)=>v+h*(k1[i]+2*k2[i]+2*k3[i]+k4[i])/6)}
function eventValue(x,vs,pp,N,mode){if(mode===1)return x[1]-x[2];if(mode===-1)return -(x[1]-x[2]);const freeV=pp.Lm/(pp.Lr+pp.Lm)*(vs-x[0]);return N-Math.abs(freeV)}
function stepEventAware(x,h,vs,pp,N){let remain=h,state=x.slice(),pieces=[],guard=0;while(remain>h*1e-8&&guard++<5){let mode=selectMode(state,vs,pp,N);if(mode===0){const a=.5*(state[1]+state[2]);state[1]=a;state[2]=a}const end=rk4Mode(state,remain,vs,pp,N,mode),g0=eventValue(state,vs,pp,N,mode),g1=eventValue(end,vs,pp,N,mode);if(g0>=-1e-9&&g1>=-1e-9){pieces.push({x0:state.slice(),x1:end.slice(),dt:remain,mode});state=end;remain=0;break}let lo=0,hi=1;for(let it=0;it<24;it++){const mid=.5*(lo+hi),xm=rk4Mode(state,remain*mid,vs,pp,N,mode),gm=eventValue(xm,vs,pp,N,mode);if(gm>=0)lo=mid;else hi=mid}const frac=Math.max(1e-7,lo),dt=remain*frac,xe=rk4Mode(state,dt,vs,pp,N,mode);if(mode!==0){const a=.5*(xe[1]+xe[2]);xe[1]=a;xe[2]=a}pieces.push({x0:state.slice(),x1:xe.slice(),dt,mode,event:true});state=xe;remain-=dt;if(remain<h*1e-7)break;const probe=Math.min(remain,h*1e-5),nextMode=selectMode(rk4Mode(state,probe,vs,pp,N,selectMode(state,vs,pp,N)),vs,pp,N);if(nextMode===0){const a=.5*(state[1]+state[2]);state[1]=a;state[2]=a}}
return {x:state,pieces}}
function integrateHalfState(x0,pp,N,steps,record=false){const Th=1/(2*pp.fs),dt=Th/steps,vs=pp.Vin;let x=x0.slice(),Q=0,ir2=0,ipk=0,impk=0,vpk=0,freeT=0,negT=0,t=0;const wave=record?[]:null,events=[];if(record)wave.push({t:0,vcr:x[0],ir:x[1],im:x[2],io:0,vs,mode:selectMode(x,vs,pp,N),edge:true});for(let s=0;s<steps;s++){const st=stepEventAware(x,dt,vs,pp,N);for(const pc of st.pieces){const io0=pc.mode===0?0:pp.n*Math.abs(pc.x0[1]-pc.x0[2]),io1=pc.mode===0?0:pp.n*Math.abs(pc.x1[1]-pc.x1[2]);Q+=.5*(io0+io1)*pc.dt;ir2+=.5*(pc.x0[1]*pc.x0[1]+pc.x1[1]*pc.x1[1])*pc.dt;ipk=Math.max(ipk,Math.abs(pc.x0[1]),Math.abs(pc.x1[1]));impk=Math.max(impk,Math.abs(pc.x0[2]),Math.abs(pc.x1[2]));vpk=Math.max(vpk,Math.abs(pc.x0[0]),Math.abs(pc.x1[0]));if(pc.mode===0)freeT+=pc.dt;if(pc.mode<0)negT+=pc.dt;t+=pc.dt;if(record){wave.push({t,vcr:pc.x1[0],ir:pc.x1[1],im:pc.x1[2],io:io1,vs,mode:pc.mode,event:!!pc.event});if(pc.event)events.push(wave.length-1)}}x=st.x;if(!x.every(Number.isFinite)||Math.max(...x.map(Math.abs))>1e8)return null}return {end:x,Q,Th,metrics:{ipk,impk,vpk,irms:Math.sqrt(ir2/Th),comm:-x0[1],freePct:100*freeT/Th,negPct:100*negT/Th},wave,events}}
function residualGain(u,pp,steps){const D=den(pp),Iscale=Math.max(1,D/Math.max(pp.Zr,1e-9)),N=u[3];if(!(N>1e-8))return [1e3,1e3,1e3,1e3];const r=integrateHalfState(u.slice(0,3),pp,N,steps,false);if(!r)return [1e3,1e3,1e3,1e3];const qload=pp.Iload*r.Th,qscale=Math.max(1e-10,Math.abs(qload));return [(r.end[0]+u[0]-sym(pp))/D,(r.end[1]+u[1])/Iscale,(r.end[2]+u[2])/Iscale,(r.Q-qload)/qscale]}
function residualFreq(u,tank,cfg,Vin,load,steps){const D=cfg.bridge==='half'?Vin/2:Vin,Iscale=Math.max(1,D/Math.max(tank.Zr,1e-9)),fs=u[3],N=tank.n*cfg.vo;if(!(fs>=cfg.fsMin*.95&&fs<=cfg.fsMax*1.05))return [1e3,1e3,1e3,1e3];const R=cfg.vo/(cfg.io*load),pp={...tank,bridge:cfg.bridge,Vin,fs,f0:cfg.f0,R},r=integrateHalfState(u.slice(0,3),pp,N,steps,false);if(!r)return [1e3,1e3,1e3,1e3];const qload=cfg.io*load*r.Th,qscale=Math.max(1e-10,Math.abs(qload));return [(r.end[0]+u[0]-sym(pp))/D,(r.end[1]+u[1])/Iscale,(r.end[2]+u[2])/Iscale,(r.Q-qload)/qscale]}
function genericGainSeeds(pp,prev){const D=den(pp),fn=pp.fs/pp.f0,N0=clamp(D*(1+.48*(1-fn)),.05*D,3.2*D),Th=1/(2*pp.fs),im=-N0*Th/(2*pp.Lm),c=.5*sym(pp),ib=D/Math.max(pp.Zr,1e-9),arr=[];if(prev&&prev.every(Number.isFinite))arr.push(prev.slice());[[-.32,0],[0,0],[.32,0],[-.12,-.10],[.12,.10]].forEach(z=>arr.push([c+z[0]*D,im+z[1]*ib,im,N0]));return arr}
function targetBranch(tk,cfg,Vin){const D=cfg.bridge==='half'?Vin/2:Vin,target=tk.n*cfg.vo/D,tol=.005;if(target>1+tol)return{name:'boost',label:'Low-frequency boost',target,lo:cfg.fsMin,hi:Math.min(cfg.fsMax,1.03*cfg.f0),side:-1};if(target<1-tol)return{name:'buck',label:'High-frequency buck',target,lo:Math.max(cfg.fsMin,.97*cfg.f0),hi:cfg.fsMax,side:1};return{name:'unity',label:'Near resonance',target,lo:Math.max(cfg.fsMin,.85*cfg.f0),hi:Math.min(cfg.fsMax,1.15*cfg.f0),side:0}}
function branchAccept(fs,b,cfg){return Number.isFinite(fs)&&fs>=b.lo-1e-6&&fs<=b.hi+1e-6&&!((b.side<0&&fs>1.03*cfg.f0)||(b.side>0&&fs<.97*cfg.f0))}
function odeSeedsAtGuide(tk,cfg,Vin,fs,prev){const D=cfg.bridge==='half'?Vin/2:Vin,N=tk.n*cfg.vo,c=.5*(cfg.bridge==='half'?Vin:0),Th=1/(2*fs),im=-N*Th/(2*tk.Lm),ib=D/Math.max(tk.Zr,1e-9),arr=[];if(prev&&prev.every(Number.isFinite))arr.push(prev.slice());arr.push([c,im,im,fs],[c-.14*D,im-.07*ib,im,fs],[c+.14*D,im+.07*ib,im,fs]);return arr}
function newtonGeneric(seed,resFn,bounds,quality,scales){let u=seed.slice();u.forEach((v,i)=>u[i]=clamp(v,bounds[i][0],bounds[i][1]));const steps=quality==='curve'?190:quality==='detail'?230:90,maxIt=quality==='curve'?18:quality==='detail'?20:12,tol=quality==='curve'?0.006:quality==='detail'?0.004:0.018;let f=resFn(u,steps),best={n:norm(f),u:u.slice(),it:0};for(let it=0;it<maxIt;it++){if(best.n<tol)break;const J=Array.from({length:4},()=>Array(4).fill(0));for(let j=0;j<4;j++){const h=2e-5*Math.max(scales[j],Math.abs(u[j])),up=u.slice();up[j]=clamp(up[j]+h,bounds[j][0],bounds[j][1]);const fp=resFn(up,steps),dh=up[j]-u[j]||h;for(let i=0;i<4;i++)J[i][j]=(fp[i]-f[i])/dh}let dx;try{dx=solveLinear(J,f.map(v=>-v))}catch(e){break}let ok=false,a=1;for(let ls=0;ls<13;ls++){const un=u.map((v,j)=>clamp(v+a*dx[j],bounds[j][0],bounds[j][1])),fn=resFn(un,steps),nn=norm(fn);if(Number.isFinite(nn)&&nn<norm(f)){u=un;f=fn;ok=true;if(nn<best.n)best={n:nn,u:u.slice(),it:it+1};break}a*=.5}if(!ok)break}return best}
function solveGain(pp,prev,quality='batch'){const D=den(pp),Iscale=Math.max(1,D/Math.max(pp.Zr,1e-9)),bounds=[[sym(pp)-3.5*D,sym(pp)+3.5*D],[-8*Iscale,8*Iscale],[-8*Iscale,8*Iscale],[.015*D,3.5*D]],scales=[Math.max(1,D),Iscale,Iscale,Math.max(1,D)];let best=null;for(const s of genericGainSeeds(pp,prev)){const r=newtonGeneric(s,(u,steps)=>residualGain(u,pp,steps),bounds,quality==='curve'?'curve':quality,scales);if(!best||r.n<best.n)best=r;if(r.n<(quality==='curve'?.006:quality==='detail'?.004:.018))break}const integ=integrateHalfState(best.u.slice(0,3),pp,best.u[3],quality==='curve'?300:quality==='detail'?340:150,false),g=best.u[3]/D,strict=Number.isFinite(g)&&g>0&&best.n<(quality==='curve'?.018:quality==='detail'?.014:.055);return {ok:strict,gain:g,residual:best.n,u:best.u,metrics:integ?integ.metrics:null}}
function solveFrequency(tk,cfg,Vin,load,prev,guideKey,localHints=[]){
 const D=cfg.bridge==='half'?Vin/2:Vin,Iscale=Math.max(1,D/Math.max(tk.Zr,1e-9)),branch=targetBranch(tk,cfg,Vin),gcfg={...cfg,fnMin:cfg.fsMin/cfg.f0,fnMax:cfg.fsMax/cfg.f0};
 if(branch.lo>=branch.hi)return{ok:false,fs:NaN,u:null,residual:1e3,metrics:null,branch:branch.label,reason:'The expected control branch is outside the allowed frequency range'};
 const gtk=trajectoryTank(tk.n,tk.k,tk.Q,gcfg),hints=[],oldHint=trajectoryGuideHints.get(guideKey);if(oldHint)hints.push(oldHint);for(let i=localHints.length-1;i>=0&&hints.length<3;i--)hints.push(localHints[i]);
 const guide=solvePoint(gtk,gcfg,Vin,load,hints);if(guide.ok)trajectoryGuideHints.set(guideKey,{mode:guide.mode,x:guide.x});
 if(!guide.ok||!branchAccept(guide.fs,branch,cfg))return{ok:false,fs:NaN,u:null,residual:1e3,metrics:null,branch:branch.label,reason:'Trajectory guidance failed on the expected control branch'};
 const baseBounds=[[sym({bridge:cfg.bridge,Vin})-3.5*D,sym({bridge:cfg.bridge,Vin})+3.5*D],[-8*Iscale,8*Iscale],[-8*Iscale,8*Iscale]],scales=[Math.max(1,D),Iscale,Iscale,Math.max(cfg.f0,1e3)],windows=[.08,.18];let chosen=null;
 for(const w of windows){const lo=Math.max(branch.lo,guide.fs-w*cfg.f0),hi=Math.min(branch.hi,guide.fs+w*cfg.f0);if(lo>=hi)continue;const bounds=baseBounds.concat([[lo,hi]]),sol=[];for(const seed of odeSeedsAtGuide(tk,cfg,Vin,clamp(guide.fs,lo,hi),prev)){const r=newtonGeneric(seed,(u,steps)=>residualFreq(u,tk,cfg,Vin,load,steps),bounds,'batch',scales),fs=r.u?.[3];if(!branchAccept(fs,branch,cfg)||fs<lo-1e-6||fs>hi+1e-6)continue;const pinned=(Math.abs(fs-lo)<.0015*cfg.f0||Math.abs(fs-hi)<.0015*cfg.f0)&&r.n>.01;if(!pinned&&r.n<.065)sol.push(r);if(r.n<.008)break}if(sol.length){sol.sort((a,b)=>Math.abs(a.u[3]-guide.fs)-Math.abs(b.u[3]-guide.fs)||a.n-b.n);chosen=sol[0];break}}
 if(!chosen)return{ok:false,fs:NaN,u:null,residual:1e3,metrics:null,branch:branch.label,reason:'ODE did not converge near the expected trajectory branch'};
 const fs=chosen.u[3],N=tk.n*cfg.vo,R=cfg.vo/(cfg.io*load),pp={...tk,bridge:cfg.bridge,Vin,fs,f0:cfg.f0,R},integ=integrateHalfState(chosen.u.slice(0,3),pp,N,210,false),ok=!!integ&&chosen.n<.065&&branchAccept(fs,branch,cfg);
 return{ok,fs,u:chosen.u,residual:chosen.n,metrics:integ?integ.metrics:null,branch:branch.label,targetGain:branch.target,guideFs:guide.fs,guideMode:guide.mode,reason:ok?'':'ODE did not converge reliably'}}
function evalPoint(tank,cfg,Vin,load,seedHint,guideKey,localHints){const r=solveFrequency(tank,cfg,Vin,load,seedHint,guideKey,localHints);if(!r.ok){return{valid:false,kind:r.residual<.2?'failed':'numerical',reason:r.reason||'ODE did not converge reliably',vin:Vin,load,residual:r.residual,branch:r.branch||'—'}}const m=r.metrics||{};return{valid:true,kind:'ok',vin:Vin,load,fs:r.fs,fn:r.fs/cfg.f0,gain:r.targetGain,residual:r.residual,u:r.u,ipk:m.ipk,irms:m.irms,vcrpk:m.vpk,impk:m.impk,comm:m.comm,freePct:m.freePct,negPct:m.negPct,branch:r.branch,guideFs:r.guideFs,guideMode:r.guideMode}}
function evalCandidate(n,k,Q,cfg,neighborSeed){const Ro=cfg.vo/cfg.io,Rac=8/(Math.PI*Math.PI)*n*n*Ro,Zr=Q*Rac,w0=2*Math.PI*cfg.f0,Lr=Zr/w0,Cr=1/(w0*Zr),Lm=k*Lr,tank={n,k,Q,Rac,Zr,Lr,Cr,Lm};const corners=[],localHints=[];let seed=null;for(let li=0;li<3;li++){for(const vi of [1,0,2]){const r=evalPoint(tank,cfg,cfg.vins[vi],cfg.loads[li],seed,li+','+vi,localHints);if(!r)return null;r.vi=vi;r.li=li;corners.push(r);if(r.valid){seed=r.u;if(r.guideMode&&r.guideFs)localHints.push({mode:r.guideMode,x:trajectoryGuideHints.get(li+','+vi)?.x})}}}corners.sort((a,b)=>a.vi-b.vi||a.li-b.li);const valid=corners.filter(c=>c.valid),bad=corners.filter(c=>!c.valid),max=fn=>valid.length?Math.max(...valid.map(fn)):NaN,min=fn=>valid.length?Math.min(...valid.map(fn)):NaN;let status='feasible',reasons=[];if(bad.length){status=bad.some(c=>c.kind==='numerical')?'numerical':'failed';reasons.push(...bad.map(c=>`${['Vin,min','Vin,typ','Vin,max'][c.vi]} / ${Math.round(c.load*100)}%：${c.reason}`))}const summary={fsMin:min(c=>c.fs),fsMax:max(c=>c.fs),ipk:max(c=>c.ipk),irms:max(c=>c.irms),vcrpk:max(c=>c.vcrpk),minComm:min(c=>c.comm),maxResidual:max(c=>c.residual)};let limitCode='N',minMargin=-1;if(!bad.length){const span=cfg.fsMax-cfg.fsMin,mLow=(summary.fsMin-cfg.fsMin)/span,mHigh=(cfg.fsMax-summary.fsMax)/span,mRes=(.065-summary.maxResidual)/.065,mComm=summary.minComm>0?Math.min(.5,summary.minComm/Math.max(1,summary.ipk)):-.05;const margins=[['F↓',mLow],['F↑',mHigh],['N',mRes],['Z',mComm]];if(cfg.iLimit>0)margins.push(['I',(cfg.iLimit-summary.ipk)/cfg.iLimit]);if(cfg.vcrLimit>0)margins.push(['V',(cfg.vcrLimit-summary.vcrpk)/cfg.vcrLimit]);margins.sort((a,b)=>a[1]-b[1]);[limitCode,minMargin]=margins[0];if(cfg.iLimit>0&&summary.ipk>cfg.iLimit){status='failed';reasons.push(`Peak current ${summary.ipk.toFixed(2)} A exceeds the constraint`)}if(cfg.vcrLimit>0&&summary.vcrpk>cfg.vcrLimit){status='failed';reasons.push(`Peak Cr voltage ${summary.vcrpk.toFixed(1)} V exceeds the constraint`)}if(status==='feasible'&&(minMargin<.08||summary.maxResidual>.035||summary.minComm<=0))status='marginal'}return{id:`n${n}-k${k}-q${Q}`,n,k,Q,Rac,Zr,Lr,Cr,Lm,status,reasons,corners,summary,seed,limitCode,minMargin}}
function predictor(prev,prev2,fs,fsPrev,fsPrev2){if(!prev)return null;if(!prev2||!Number.isFinite(fsPrev2))return prev.slice();const r=(fs-fsPrev)/(fsPrev-fsPrev2||1);return prev.map((v,i)=>v+r*(v-prev2[i]))}
function detailCurve(candidate,cfg,vin){const loads=cfg.loads,curves=[],NPTS=101,grid=Array.from({length:NPTS},(_,i)=>cfg.fsMin+(cfg.fsMax-cfg.fsMin)*i/(NPTS-1)),center=grid.reduce((bi,x,i)=>Math.abs(x-cfg.f0)<Math.abs(grid[bi]-cfg.f0)?i:bi,0);for(const load of loads){const Iload=cfg.io*load,pts=Array(NPTS).fill(null),solveAt=(idx,seed)=>{const fs=grid[idx],pp={...candidate,bridge:cfg.bridge,Vin:vin,fs,f0:cfg.f0,Iload},r=solveGain(pp,seed,'curve');pts[idx]={fs,gain:r.ok?r.gain:NaN,residual:r.residual,u:r.u,ok:r.ok,metrics:r.metrics};return r};let c=solveAt(center,null),p1=c.u&&c.u.every(Number.isFinite)?c.u:null,p2=null,fp1=grid[center],fp2=NaN;for(let i=center-1;i>=0;i--){const pred=predictor(p1,p2,grid[i],fp1,fp2),r=solveAt(i,pred||p1);if(r.u&&r.u.every(Number.isFinite)){p2=p1;fp2=fp1;p1=r.u;fp1=grid[i]}else{p2=null;fp2=NaN}}p1=c.u&&c.u.every(Number.isFinite)?c.u:null;p2=null;fp1=grid[center];fp2=NaN;for(let i=center+1;i<NPTS;i++){const pred=predictor(p1,p2,grid[i],fp1,fp2),r=solveAt(i,pred||p1);if(r.u&&r.u.every(Number.isFinite)){p2=p1;fp2=fp1;p1=r.u;fp1=grid[i]}else{p2=null;fp2=NaN}}curves.push({load,pts})}return curves}
function fullWave(candidate,cfg,corner){const pp={...candidate,bridge:cfg.bridge,Vin:corner.vin,fs:corner.fs,f0:cfg.f0,Iload:cfg.io*corner.load},N=candidate.n*cfg.vo,seed=corner.u,solF=solveFrequency(candidate,cfg,corner.vin,corner.load,seed,corner.li+','+corner.vi,[]),u=solF.ok?solF.u:seed,steps=300,high=integrateHalfState(u.slice(0,3),pp,N,steps,true);if(!high)return null;const lo=cfg.bridge==='half'?0:-pp.Vin;let x=high.end.slice(),t0=high.Th,oneCycle=high.wave.slice();const low=integrateHalfState(x,{...pp,Vin:lo},N,steps,true);if(!low)return null;const lowPts=low.wave.slice(1).map(p=>({...p,t:p.t+t0,vs:lo,edge:false}));if(lowPts.length)lowPts[0].edge=true;oneCycle=oneCycle.concat(lowPts);const Ts=2*high.Th,wave=[];for(let cyc=0;cyc<3;cyc++){oneCycle.forEach((p,i)=>{if(cyc>0&&i===0)return;wave.push({...p,t:p.t+cyc*Ts,edge:p.edge})})}return {fs:pp.fs,Vo:N/candidate.n,residual:solF.residual,points:wave,statePoints:oneCycle,cycles:3,metrics:{...high.metrics,freePct:(high.metrics.freePct+low.metrics.freePct)/2},events:(high.events||[]).concat((low.events||[]).map(i=>i+high.wave.length-1))}}
onmessage=e=>{const m=e.data;if(m.type==='cancel'){cancelled=true;return}cancelled=false;if(m.type==='run'){const cfg=m.config,total=cfg.nList.length*cfg.kList.length*cfg.qList.length,out=[];trajectoryGuideHints=new Map();let done=0,t0=performance.now();for(let ni=0;ni<cfg.nList.length;ni++){trajectoryGuideHints=new Map();const n=cfg.nList[ni],ks=ni%2===0?cfg.kList:cfg.kList.slice().reverse();for(let ki=0;ki<ks.length;ki++){const k=ks[ki],qs=(ni+ki)%2===0?cfg.qList:cfg.qList.slice().reverse();for(const Q of qs){if(cancelled){postMessage({type:'cancelled',token:m.token});return}const c=evalCandidate(n,k,Q,cfg,null);if(c)out.push(c);done++;postMessage({type:'progress',token:m.token,done,total,label:`n=${n}, k=${k}, Q=${Q}`})}}}postMessage({type:'done',token:m.token,candidates:out,elapsed:(performance.now()-t0)/1000})}else if(m.type==='curve'){postMessage({type:'curveDone',requestId:m.requestId,curves:detailCurve(m.candidate,m.config,m.vin),vin:m.vin})}else if(m.type==='wave'){postMessage({type:'waveDone',requestId:m.requestId,wave:fullWave(m.candidate,m.config,m.corner)})}}
}
function createWorker(handler){const src=`(${workerMain.toString()})()`,w=new Worker(URL.createObjectURL(new Blob([src],{type:'text/javascript'})));w.onmessage=handler;return w}
function ensureWorker(){if(worker)worker.terminate();worker=createWorker(handleWorker)}
function handleWorker(e){const m=e.data;if(m.type==='curveDone'&&m.requestId===detailReq){$('curveBtn').disabled=false;$('curveBtn').textContent=zh?'计算增益包络':'Calculate Gain Envelope';renderGainPlot(m.curves,m.vin)}else if(m.type==='waveDone'&&m.requestId===detailReq){$('waveBtn').disabled=false;$('waveBtn').textContent=ui.recalc;lastWave=m.wave;if(m.wave){renderStatePlot(m.wave);renderStateSummary(m.wave);renderWavePlot(m.wave)}else{drawPlaceholder('statePlot',ui.detailFail);drawPlaceholder('wavePlot',ui.detailFail)}}}
function stopSearchWorkers(){for(const w of searchWorkers)try{w.terminate()}catch{}searchWorkers=[];searchState=null}
function startParallelSearch(cfg){stopSearchWorkers();if(worker){try{worker.terminate()}catch{}worker=null}const parts=cfg.nList.map(n=>({...cfg,nList:[n]})),token=runToken,state={token,start:performance.now(),parts,progress:Array(parts.length).fill(0),totals:parts.map(c=>c.kList.length*c.qList.length),results:Array(parts.length),done:0};searchState=state;parts.forEach((pc,i)=>{const w=createWorker(e=>handleSearchMessage(e,i));searchWorkers.push(w);w.postMessage({type:'run',token,config:pc})})}
function handleSearchMessage(e,idx){const m=e.data,s=searchState;if(!s||m.token!==s.token)return;if(m.type==='progress'){s.progress[idx]=m.done;const done=s.progress.reduce((a,b)=>a+b,0),total=s.totals.reduce((a,b)=>a+b,0);$('progressBar').style.width=(100*done/total)+'%';$('progressText').textContent=ui.progress(done,total,m.label)}else if(m.type==='done'){s.results[idx]=m.candidates;s.progress[idx]=s.totals[idx];s.done++;if(s.done===s.parts.length){allCandidates=s.results.flat();const elapsed=(performance.now()-s.start)/1000;$('runBtn').disabled=false;$('cancelBtn').disabled=true;$('progressBar').style.width='100%';$('progressText').textContent=ui.complete(allCandidates.length,elapsed);$('mTime').textContent=fmt(elapsed,1)+' s';const keep=searchWorkers[0];for(let i=1;i<searchWorkers.length;i++)try{searchWorkers[i].terminate()}catch{}searchWorkers=keep?[keep]:[];worker=keep||null;if(worker)worker.onmessage=handleWorker;rankCandidates();activeRatio=currentConfig.nList[Math.floor(currentConfig.nList.length/2)];renderAll();searchState=null}}else if(m.type==='cancelled'){stopSearchWorkers();$('runBtn').disabled=false;$('cancelBtn').disabled=true;$('progressText').textContent=ui.cancelled}}
$('runBtn').onclick=()=>{try{currentConfig=readConfig()}catch(err){alert(err.message);return}runToken++;selected=null;allCandidates=[];$('runBtn').disabled=true;$('cancelBtn').disabled=false;$('progressBar').style.width='0%';$('progressText').textContent=ui.running;drawPlaceholder('gainPlot',ui.runEnvelope);drawPlaceholder('statePlot',ui.runState);drawPlaceholder('wavePlot',ui.runWave);startParallelSearch(currentConfig)};$('cancelBtn').onclick=()=>{stopSearchWorkers();if(worker){try{worker.terminate()}catch{}worker=null}$('runBtn').disabled=false;$('cancelBtn').disabled=true;$('progressText').textContent=ui.cancelled};
function rankCandidates(){const valid=allCandidates.filter(c=>c.status==='feasible'||c.status==='marginal');valid.sort((a,b)=>(b.minMargin-a.minMargin)||((a.summary.irms||1e9)-(b.summary.irms||1e9))||((a.summary.fsMax-a.summary.fsMin)-(b.summary.fsMax-b.summary.fsMin)));valid.forEach((c,i)=>c.rank=i+1);allCandidates.forEach(c=>{if(!c.rank)c.rank=9999})}
function renderAll(){const f=allCandidates.filter(c=>c.status==='feasible').length,m=allCandidates.filter(c=>c.status==='marginal').length;$('mTotal').textContent=allCandidates.length;$('mFeasible').textContent=f;$('mMarginal').textContent=m;$('mFailed').textContent=allCandidates.length-f-m;renderRatioOverview();renderMatrix();renderRecommendations();const first=allCandidates.filter(c=>c.rank<9999).sort((a,b)=>a.rank-b.rank)[0]||allCandidates[0];if(first)selectCandidate(first.id)}
function statusBaseColor(c){if(c.status==='numerical')return '#e2e8f0';if(c.status==='failed')return '#fee2e2';if(c.status==='marginal')return '#fef3c7';return '#d1fae5'}
function marginColor(c){if(c.status==='numerical')return '#e2e8f0';if(c.status==='failed')return '#fee2e2';const t=clamp((c.minMargin+0.02)/.25,0,1),h=38+105*t,s=72,l=88-18*t;return `hsl(${h} ${s}% ${l}%)`}
function renderRatioOverview(){const wrap=$('ratioOverview');wrap.innerHTML=currentConfig.nList.map(n=>{const cs=allCandidates.filter(c=>c.n===n),ok=cs.filter(c=>c.status==='feasible'||c.status==='marginal'),best=ok.slice().sort((a,b)=>b.minMargin-a.minMargin)[0],cells=cs.sort((a,b)=>a.k-b.k||a.Q-b.Q).map(c=>`<div class="mini-cell" title="k=${c.k}, Q=${fmt(c.Q,2)} · ${statusLabel[c.status]} · ${fmt(c.minMargin*100,1)}%" style="background:${marginColor(c)}"></div>`).join('');return `<div class="ratio-overview ${n===activeRatio?'active':''}" data-n="${n}"><div class="ratio-head"><b>n = ${n}</b><span>${ui.feasibleMarginal} ${ok.length}/${currentConfig.kList.length*currentConfig.qList.length}<br>${ui.bestMargin} ${best?fmt(best.minMargin*100,1)+'%':'—'}</span></div><div class="mini-map">${cells}</div></div>`}).join('');wrap.querySelectorAll('[data-n]').forEach(el=>el.onclick=()=>{activeRatio=+el.dataset.n;renderRatioOverview();renderMatrix()})}
function metricValue(c,metric){const s=c.summary||{};if(metric==='margin')return c.minMargin;if(metric==='fsmax')return s.fsMax/1e3;if(metric==='ipk')return s.ipk;if(metric==='irms')return s.irms;if(metric==='vcrpk')return s.vcrpk;if(metric==='comm')return s.minComm;return NaN}
function metricText(c,metric){const v=metricValue(c,metric);if(metric==='margin')return Number.isFinite(v)?`${v>=0?'+':''}${fmt(v*100,0)}%`:'—';if(metric==='fsmax')return `${fmt(v,0)}k`;if(metric==='vcrpk')return `${fmt(v,0)}V`;return `${fmt(v,1)}A`}
function metricBackground(c,metric,cs){if(metric==='margin')return marginColor(c);if(c.status==='numerical')return '#e2e8f0';if(c.status==='failed')return '#fee2e2';const vals=cs.map(x=>metricValue(x,metric)).filter(Number.isFinite),lo=Math.min(...vals),hi=Math.max(...vals),v=metricValue(c,metric);let t=(v-lo)/(hi-lo||1);if(metric==='comm')t=1-t;const h=140-105*t;return `hsl(${h} 72% ${90-12*Math.abs(t-.5)*2}%)`}
$('matrixMetric').onchange=renderMatrix;
function renderMatrix(){if(!allCandidates.length){$('matrix').innerHTML=`<div class="empty">${ui.runPopulate}</div>`;return}const cs=allCandidates.filter(c=>c.n===activeRatio),ks=currentConfig.kList,qs=currentConfig.qList,metric=$('matrixMetric').value;$('activeRatioLabel').textContent=`n = ${activeRatio}`;$('matrix').style.gridTemplateColumns=`82px repeat(${qs.length},minmax(90px,1fr))`;let html='<div class="axis-cell">k ↓ / Q →</div>'+qs.map(q=>`<div class="axis-cell">Q ${fmt(q,2)}</div>`).join('');for(const k of ks){html+=`<div class="axis-cell">k = ${k}</div>`;for(const q of qs){const c=cs.find(x=>x.k===k&&Math.abs(x.Q-q)<1e-9);if(!c){html+='<div class="cell"></div>';continue}const s=c.summary||{},reason=c.reasons?.[0]||'',bg=metricBackground(c,metric,cs),main=metricText(c,metric),sub=c.status==='failed'||c.status==='numerical'?reason:`fs ${fmt(s.fsMin/1e3,0)}–${fmt(s.fsMax/1e3,0)}k<br>Ipk ${fmt(s.ipk,1)} A`;html+=`<div class="cell ${selected?.id===c.id?'selected':''}" data-id="${c.id}" style="background:${bg};border-color:${c.status==='numerical'?'#cbd5e1':c.status==='failed'?'#f3a7a7':'rgba(15,23,42,.14)'}"><div class="top"><span>${statusLabel[c.status]}</span><span class="limit-tag">${c.limitCode||'N'}</span></div><div class="margin">${main}</div><div class="mini">${sub}</div></div>`}}$('matrix').innerHTML=html;$('matrix').querySelectorAll('[data-id]').forEach(el=>el.onclick=()=>selectCandidate(el.dataset.id))}
function renderRecommendations(){const rows=allCandidates.slice().sort((a,b)=>a.rank-b.rank).slice(0,5);$('recommendBody').innerHTML=rows.map(c=>{const s=c.summary;return `<tr class="click-row ${selected?.id===c.id?'active':''}" data-id="${c.id}"><td>${c.rank<9999?'#'+c.rank:'—'} <span class="pill ${c.status}">${statusLabel[c.status]}</span></td><td>${c.n}</td><td>${c.k}</td><td>${fmt(c.Q,2)}</td><td>${fmt(c.Lr*1e6,2)}</td><td>${fmt(c.Lm*1e6,2)}</td><td>${fmt(c.Cr*1e9,2)}</td><td>${fmt(s.fsMin/1e3,0)}–${fmt(s.fsMax/1e3,0)}</td><td>${fmt(s.ipk,2)}</td><td>${fmt(s.irms,2)}</td><td>${fmt(s.vcrpk,0)}</td><td>${Number.isFinite(c.minMargin)?(c.minMargin>=0?'+':'')+fmt(c.minMargin*100,1)+'%':'—'}</td><td>${c.limitCode||'N'}</td></tr>`}).join('');$('recommendBody').querySelectorAll('[data-id]').forEach(el=>el.onclick=()=>selectCandidate(el.dataset.id))}
function selectCandidate(id){selected=allCandidates.find(c=>c.id===id);if(!selected)return;activeRatio=selected.n;selectedCornerIndex=worstCornerIndex(selected);renderRatioOverview();renderMatrix();renderRecommendations();renderSelected();renderCorners();$('curveBtn').disabled=false;drawPlaceholder('gainPlot',ui.clickEnvelope);renderEnvelopeSummary();$('waveBtn').disabled=false;requestWave()}
function worstCornerIndex(c){let idx=0,b=-Infinity;c.corners.forEach((x,i)=>{const v=x.valid?(x.ipk||0):-1;if(v>b){b=v;idx=i}});return idx}
function renderSelected(){const c=selected,s=c.summary,reason=c.reasons?.length?c.reasons.join('<br>'):(c.status==='feasible'?ui.allReachable:ui.tightMargin);$('selectedPanel').innerHTML=`<div class="design-title"><h3>n=${c.n}, k=${c.k}, Q=${fmt(c.Q,2)}</h3><div class="margin-badge">${ui.worstMargin} ${Number.isFinite(c.minMargin)?(c.minMargin>=0?'+':'')+fmt(c.minMargin*100,1)+'%':'—'}</div></div><div class="kv"><div><b>Lr</b><span>${fmt(c.Lr*1e6,3)} µH</span></div><div><b>Lm</b><span>${fmt(c.Lm*1e6,3)} µH</span></div><div><b>Cr</b><span>${fmt(c.Cr*1e9,3)} nF</span></div><div><b>Zr</b><span>${fmt(c.Zr,3)} Ω</span></div><div><b>${ui.requiredFs}</b><span>${fmt(s.fsMin/1e3,1)}–${fmt(s.fsMax/1e3,1)} kHz</span></div><div><b>${ui.limit}</b><span>${c.limitCode||'N'}</span></div><div><b>${ui.worstIpk}</b><span>${fmt(s.ipk,2)} A</span></div><div><b>${ui.worstIrms}</b><span>${fmt(s.irms,2)} A</span></div><div><b>${ui.worstVcr}</b><span>${fmt(s.vcrpk,1)} V</span></div><div><b>${ui.minComm}</b><span>${fmt(s.minComm,2)} A</span></div></div><div class="status-box ${c.status}"><b>${statusLabel[c.status]}</b><br>${reason}</div>`}
function cornerName(c){return `${['Vin,min','Vin,typ','Vin,max'][c.vi]} / ${Math.round(c.load*100)}%`}
function renderCorners(){$('cornerBody').innerHTML=selected.corners.map((c,i)=>`<tr class="click-row ${i===selectedCornerIndex?'active':''}" data-i="${i}"><td>${cornerName(c)}</td><td>${fmt(c.vin,0)}</td><td>${fmt(c.load*100,0)}%</td><td>${fmt(c.fs/1e3,2)}</td><td>${fmt(c.fn,3)}</td><td>${c.branch?branchLabel(c.branch):'—'}</td><td>${fmt(c.ipk,3)}</td><td>${fmt(c.irms,3)}</td><td>${fmt(c.vcrpk,1)}</td><td>${fmt(c.comm,3)}</td><td>${fmt(c.freePct,1)}%</td><td>${fmt(c.residual,4)}</td><td><span class="pill ${c.valid?'feasible':c.kind}">${c.valid?ui.pass:c.reason}</span></td></tr>`).join('');$('cornerBody').querySelectorAll('[data-i]').forEach(el=>el.onclick=()=>{selectedCornerIndex=+el.dataset.i;renderCorners();requestWave()})}
function svgAdd(svg,tag,a,text){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(a||{}).forEach(([k,v])=>e.setAttribute(k,v));if(text!=null)e.textContent=text;svg.appendChild(e);return e}
function drawPlaceholder(id,msg){const s=$(id);s.innerHTML='';const vb=(s.getAttribute('viewBox')||'0 0 760 390').split(/\s+/).map(Number),W=vb[2],H=vb[3];svgAdd(s,'rect',{x:0,y:0,width:W,height:H,fill:'#fff'});svgAdd(s,'text',{x:W/2,y:H/2,'text-anchor':'middle','font-size':18,fill:'#94a3b8'},msg)}

$('curveBtn').onclick=()=>{if(!selected)return;const vin=currentConfig.vinTyp;$('curveBtn').disabled=true;$('curveBtn').innerHTML=`<span class="spinner"></span>${ui.calculating}`;drawPlaceholder('gainPlot',ui.calcEnvelope);worker.postMessage({type:'curve',requestId:++detailReq,candidate:selected,config:currentConfig,vin})};
function targetGainForVin(vin){return selected.n*currentConfig.vo/(currentConfig.bridge==='half'?vin/2:vin)}
function renderEnvelopeSummary(){if(!selected||!currentConfig)return;const s=selected.summary||{},gHi=targetGainForVin(currentConfig.vinMin),gLo=targetGainForVin(currentConfig.vinMax),valid=(selected.corners||[]).filter(c=>c.valid&&Number.isFinite(c.fs)),fmin=valid.length?Math.min(...valid.map(c=>c.fs)):NaN,fmax=valid.length?Math.max(...valid.map(c=>c.fs)):NaN,lowMargin=fmin-currentConfig.fsMin,highMargin=currentConfig.fsMax-fmax;let worst=null;if(valid.length){worst=valid.slice().sort((a,b)=>Math.min(a.fs-currentConfig.fsMin,currentConfig.fsMax-a.fs)-Math.min(b.fs-currentConfig.fsMin,currentConfig.fsMax-b.fs))[0]}const items=[[ui.targetGain,`${fmt(gLo,3)}–${fmt(gHi,3)}`],[ui.requiredFsRange,Number.isFinite(fmin)?`${fmt(fmin/1e3,0)}–${fmt(fmax/1e3,0)} kHz`:'—'],[ui.lowMargin,Number.isFinite(lowMargin)?`${lowMargin>=0?'+':''}${fmt(lowMargin/1e3,0)} kHz`:'—'],[ui.highMargin,Number.isFinite(highMargin)?`${highMargin>=0?'+':''}${fmt(highMargin/1e3,0)} kHz`:'—'],[ui.tightestCorner,worst?cornerName(worst):'—']];$('curveSummary').innerHTML=items.map(x=>`<div class="envelope-chip"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}
function renderGainPlot(curves,vin){const svg=$('gainPlot');svg.innerHTML='';const W=1220,H=520,m={l:78,r:30,t:40,b:62},xmin=currentConfig.fsMin/1e3,xmax=currentConfig.fsMax/1e3,vals=curves.flatMap(c=>c.pts.map(p=>p.gain)).filter(Number.isFinite),gHi=targetGainForVin(currentConfig.vinMin),gLo=targetGainForVin(currentConfig.vinMax);if(!vals.length){drawPlaceholder('gainPlot',ui.curveNoConverge);return}const ymin=Math.max(0,Math.min(...vals,gLo)*.90),ymax=Math.max(...vals,gHi)*1.08,X=x=>m.l+(x-xmin)/(xmax-xmin)*(W-m.l-m.r),Y=y=>H-m.b-(y-ymin)/(ymax-ymin)*(H-m.t-m.b);svgAdd(svg,'rect',{x:0,y:0,width:W,height:H,fill:'#fff'});
// target gain band from input range
svgAdd(svg,'rect',{x:m.l,y:Y(gHi),width:W-m.l-m.r,height:Math.max(1,Y(gLo)-Y(gHi)),fill:'#fee2e2',opacity:.42});
for(let i=0;i<=6;i++){const y=ymin+(ymax-ymin)*i/6,yp=Y(y);svgAdd(svg,'line',{x1:m.l,y1:yp,x2:W-m.r,y2:yp,stroke:'#e5e7eb'});svgAdd(svg,'text',{x:m.l-9,y:yp+4,'text-anchor':'end','font-size':11,fill:'#64748b'},fmt(y,2))}
for(let i=0;i<=8;i++){const x=xmin+(xmax-xmin)*i/8,xp=X(x);svgAdd(svg,'line',{x1:xp,y1:m.t,x2:xp,y2:H-m.b,stroke:'#eef2f7'});svgAdd(svg,'text',{x:xp,y:H-m.b+23,'text-anchor':'middle','font-size':11,fill:'#64748b'},fmt(x,0))}
svgAdd(svg,'line',{x1:X(currentConfig.f0/1e3),y1:m.t,x2:X(currentConfig.f0/1e3),y2:H-m.b,stroke:'#94a3b8','stroke-dasharray':'4 5'});svgAdd(svg,'text',{x:X(currentConfig.f0/1e3)+5,y:m.t+13,'font-size':10,fill:'#64748b'},'f0');
// Load envelope across all valid curves
const npts=Math.max(...curves.map(c=>c.pts.length)),runs=[];let run=[];for(let j=0;j<npts;j++){const ps=curves.map(c=>c.pts[j]).filter(p=>p&&Number.isFinite(p.gain));if(ps.length>=2){run.push({fs:ps[0].fs/1e3,lo:Math.min(...ps.map(p=>p.gain)),hi:Math.max(...ps.map(p=>p.gain))})}else if(run.length){runs.push(run);run=[]}}if(run.length)runs.push(run);runs.forEach(r=>{if(r.length<2)return;const top=r.map((p,i)=>(i?'L':'M')+X(p.fs)+','+Y(p.hi)).join(' '),bot=r.slice().reverse().map(p=>'L'+X(p.fs)+','+Y(p.lo)).join(' ');svgAdd(svg,'path',{d:top+' '+bot+' Z',fill:'#bfdbfe',opacity:.52,stroke:'none'})});
const colors=['#06b6d4','#2563eb','#0f3f78'];curves.forEach((c,i)=>{let seg=[];const flush=()=>{if(seg.length>1)svgAdd(svg,'path',{d:seg.map((p,j)=>(j?'L':'M')+X(p.fs/1e3)+','+Y(p.gain)).join(' '),fill:'none',stroke:colors[i],'stroke-width':i===1?3.2:2.5,'stroke-linejoin':'round'});seg=[]};c.pts.forEach(p=>{if(Number.isFinite(p.gain))seg.push(p);else flush()});flush()});
// input target lines
svgAdd(svg,'line',{x1:m.l,y1:Y(gHi),x2:W-m.r,y2:Y(gHi),stroke:'#dc2626','stroke-width':2,'stroke-dasharray':'8 6'});svgAdd(svg,'text',{x:W-m.r-5,y:Y(gHi)-7,'text-anchor':'end','font-size':11,'font-weight':850,fill:'#b91c1c'},`Vin,min target ${fmt(gHi,3)}`);svgAdd(svg,'line',{x1:m.l,y1:Y(gLo),x2:W-m.r,y2:Y(gLo),stroke:'#f97316','stroke-width':2,'stroke-dasharray':'8 6'});svgAdd(svg,'text',{x:W-m.r-5,y:Y(gLo)+16,'text-anchor':'end','font-size':11,'font-weight':850,fill:'#c2410c'},`Vin,max target ${fmt(gLo,3)}`);
// 9 exact operating points
const loadColors=colors;for(const c of selected.corners||[]){if(!c.valid||!Number.isFinite(c.fs))continue;const li=currentConfig.loads.findIndex(x=>Math.abs(x-c.load)<1e-7),g=targetGainForVin(c.vin),cx=X(c.fs/1e3),cy=Y(g);if(cx<m.l||cx>W-m.r||cy<m.t||cy>H-m.b)continue;svgAdd(svg,'circle',{cx,cy,r:5.2,fill:loadColors[Math.max(0,li)]||'#111827',stroke:'#fff','stroke-width':2});svgAdd(svg,'circle',{cx,cy,r:6.5,fill:'none',stroke:'#111827','stroke-width':.7,opacity:.45})}
// legends
svgAdd(svg,'rect',{x:m.l+10,y:m.t+9,width:24,height:10,rx:3,fill:'#bfdbfe',opacity:.7});svgAdd(svg,'text',{x:m.l+40,y:m.t+18,'font-size':11,'font-weight':800,fill:'#475569'},ui.loadEnvelope);curves.forEach((c,i)=>{const x=m.l+142+i*135;svgAdd(svg,'line',{x1:x,y1:m.t+14,x2:x+28,y2:m.t+14,stroke:colors[i],'stroke-width':i===1?3.2:2.5});svgAdd(svg,'text',{x:x+35,y:m.t+18,'font-size':11,'font-weight':800,fill:colors[i]},`${Math.round(c.load*100)}% ${ui.load}`)});svgAdd(svg,'circle',{cx:m.l+560,cy:m.t+14,r:5,fill:'#2563eb',stroke:'#111827','stroke-width':.7});svgAdd(svg,'text',{x:m.l+572,y:m.t+18,'font-size':11,'font-weight':800,fill:'#475569'},ui.solvedPoints);
svgAdd(svg,'line',{x1:m.l,y1:H-m.b,x2:W-m.r,y2:H-m.b,stroke:'#111827'});svgAdd(svg,'line',{x1:m.l,y1:m.t,x2:m.l,y2:H-m.b,stroke:'#111827'});svgAdd(svg,'text',{x:W/2,y:H-15,'text-anchor':'middle','font-size':13,fill:'#334155'},ui.fsAxis);svgAdd(svg,'text',{x:21,y:H/2,'text-anchor':'middle','font-size':13,fill:'#334155',transform:`rotate(-90 21 ${H/2})`},ui.gainAxis);renderEnvelopeSummary()}
$('waveBtn').onclick=requestWave;
function requestWave(){if(!selected)return;const c=selected.corners[selectedCornerIndex];if(!c||!c.valid){drawPlaceholder('statePlot',ui.invalidPoint);drawPlaceholder('wavePlot',ui.invalidPoint);$('stateSummary').innerHTML=`<div class="empty">${ui.noSteady}</div>`;return}$('stateHint').textContent=`${cornerName(c)} · fs=${fmt(c.fs/1e3,2)} kHz`;$('waveHint').textContent=`${cornerName(c)} · fs=${fmt(c.fs/1e3,2)} kHz`;$('waveBtn').disabled=true;$('waveBtn').innerHTML=`<span class="spinner"></span>${ui.calculating}`;drawPlaceholder('statePlot',ui.generatingState);drawPlaceholder('wavePlot',ui.generatingWave);worker.postMessage({type:'wave',requestId:++detailReq,candidate:selected,config:currentConfig,corner:c})}
function renderStatePlot(w){const svg=$('statePlot');svg.innerHTML='';const pts=w.statePoints||w.points||[],W=900,H=520,m={l:76,r:24,t:32,b:58};if(pts.length<2){drawPlaceholder('statePlot',ui.stateCalcFail);return}const xs=pts.map(p=>p.vcr),ys=pts.map(p=>p.ir),xmin=Math.min(...xs),xmax=Math.max(...xs),yabs=Math.max(...ys.map(Math.abs),1),xpad=.09*(xmax-xmin||1),X=x=>m.l+(x-(xmin-xpad))/(xmax-xmin+2*xpad)*(W-m.l-m.r),Y=y=>H-m.b-(y+yabs*1.12)/(2*yabs*1.12)*(H-m.t-m.b);svgAdd(svg,'rect',{x:0,y:0,width:W,height:H,fill:'#fff'});for(let i=0;i<=6;i++){const xv=xmin-xpad+(xmax-xmin+2*xpad)*i/6,xp=X(xv);svgAdd(svg,'line',{x1:xp,y1:m.t,x2:xp,y2:H-m.b,stroke:'#eef2f7'});svgAdd(svg,'text',{x:xp,y:H-m.b+22,'text-anchor':'middle','font-size':11,fill:'#64748b'},fmt(xv,0))}for(let i=0;i<=6;i++){const yv=-yabs*1.12+2*yabs*1.12*i/6,yp=Y(yv);svgAdd(svg,'line',{x1:m.l,y1:yp,x2:W-m.r,y2:yp,stroke:'#eef2f7'});svgAdd(svg,'text',{x:m.l-8,y:yp+4,'text-anchor':'end','font-size':11,fill:'#64748b'},fmt(yv,1))}svgAdd(svg,'line',{x1:m.l,y1:Y(0),x2:W-m.r,y2:Y(0),stroke:'#94a3b8'});const modeColor={1:'#2563eb',0:'#f59e0b','-1':'#7c3aed'};let seg=[pts[0]],mode=pts[1]?.mode??pts[0].mode;const flush=()=>{if(seg.length>1)svgAdd(svg,'path',{d:seg.map((p,i)=>(i?'L':'M')+X(p.vcr)+','+Y(p.ir)).join(' '),fill:'none',stroke:modeColor[mode], 'stroke-width':3.2,'stroke-linecap':'round','stroke-linejoin':'round'});seg=[]};for(let i=1;i<pts.length;i++){const p=pts[i];if(p.mode!==mode){flush();seg=[pts[i-1],p];mode=p.mode}else seg.push(p)}flush();const edges=pts.map((p,i)=>p.edge?i:-1).filter(i=>i>=0);edges.forEach((idx,j)=>{const p=pts[idx];svgAdd(svg,'circle',{cx:X(p.vcr),cy:Y(p.ir),r:5,fill:'#111827',stroke:'#fff','stroke-width':1.5});svgAdd(svg,'text',{x:X(p.vcr)+8,y:Y(p.ir)-8,'font-size':12,'font-weight':900,fill:'#111827'},j===0?'A':'C')});for(let i=14;i<pts.length;i+=Math.max(20,Math.floor(pts.length/18))){const a=pts[i-1],b=pts[i],dx=X(b.vcr)-X(a.vcr),dy=Y(b.ir)-Y(a.ir),l=Math.hypot(dx,dy)||1,ux=dx/l,uy=dy/l,x=X(b.vcr),y=Y(b.ir);svgAdd(svg,'path',{d:`M${x},${y} l${-7*ux+4*uy},${-7*uy-4*ux} M${x},${y} l${-7*ux-4*uy},${-7*uy+4*ux}`,stroke:modeColor[b.mode], 'stroke-width':1.5,fill:'none'})}svgAdd(svg,'line',{x1:m.l,y1:H-m.b,x2:W-m.r,y2:H-m.b,stroke:'#111827'});svgAdd(svg,'line',{x1:m.l,y1:m.t,x2:m.l,y2:H-m.b,stroke:'#111827'});svgAdd(svg,'text',{x:W/2,y:H-14,'text-anchor':'middle','font-size':14,'font-weight':800,fill:'#334155'},'vCr [V]');svgAdd(svg,'text',{x:22,y:H/2,'text-anchor':'middle','font-size':14,'font-weight':800,fill:'#334155',transform:`rotate(-90 22 ${H/2})`},'iLr [A]');svgAdd(svg,'text',{x:W/2,y:22,'text-anchor':'middle','font-size':15,'font-weight':850,fill:'#111827'},`${zh?'ODE 状态平面':'ODE state-plane'} · Vo=${fmt(w.Vo,3)} V · fs=${fmt(w.fs/1e3,2)} kHz`)}
function renderStateSummary(w){const c=selected.corners[selectedCornerIndex],pts=w.statePoints||w.points||[],free=pts.filter(p=>p.mode===0).length/Math.max(1,pts.length),trans=[];for(let i=1;i<pts.length;i++)if(pts[i].mode!==pts[i-1].mode)trans.push({from:pts[i-1].mode,to:pts[i].mode,t:pts[i].t});const modeText=free>.01?ui.discontinuous:ui.continuous,worst=free>.15?ui.longFree:free>.01?ui.hasFree:ui.clampStates;$('stateSummary').innerHTML=`<h3>${cornerName(c)}</h3><div class="mode-card"><b>${modeText}</b><br>${worst}</div><div class="kv"><div><b>${ui.switchingFrequency}</b><span>${fmt(w.fs/1e3,2)} kHz</span></div><div><b>fs / f0</b><span>${fmt(w.fs/currentConfig.f0,3)}</span></div><div><b>Ir,pk</b><span>${fmt(c.ipk,3)} A</span></div><div><b>Ir,rms</b><span>${fmt(c.irms,3)} A</span></div><div><b>VCr,pk</b><span>${fmt(c.vcrpk,1)} V</span></div><div><b>${ui.commutationCurrent}</b><span>${fmt(c.comm,3)} A</span></div><div><b>${ui.freeInterval}</b><span>${fmt(c.freePct,1)}%</span></div><div><b>${ui.stateTransitions}</b><span>${trans.length}</span></div></div><div class="mode-card" style="margin-top:10px"><b>${ui.readPlot}</b><br>${ui.readPlotText}</div>`}
function renderWavePlot(w){const svg=$('wavePlot');svg.innerHTML='';const W=1220,H=520,left=68,right=18,top=24,bottom=42,gap=12,rows=4,rh=(H-top-bottom-gap*(rows-1))/rows,pts=w.points;if(!pts?.length){drawPlaceholder('wavePlot',ui.waveCalcFail);return}const tmax=pts[pts.length-1].t*1e6,X=t=>left+t*1e6/tmax*(W-left-right),series=[['vCr [V]','vcr'],['iLr / iLm [A]','curr'],[zh?'整流电流 [A]':'Rectified current [A]','io'],[zh?'桥臂电压 [V]':'Bridge voltage [V]','vs']];svgAdd(svg,'rect',{x:0,y:0,width:W,height:H,fill:'#fff'});series.forEach((s,ri)=>{const y0=top+ri*(rh+gap),keys=s[1]==='curr'?['ir','im']:[s[1]],values=pts.flatMap(p=>keys.map(k=>p[k])).filter(Number.isFinite),mn=Math.min(...values),mx=Math.max(...values),pad=.12*(mx-mn||1),lo=mn-pad,hi=mx+pad,Y=v=>y0+rh-(v-lo)/(hi-lo||1)*rh;for(let j=0;j<=4;j++){const x=left+(W-left-right)*j/4;svgAdd(svg,'line',{x1:x,y1:y0,x2:x,y2:y0+rh,stroke:'#eef2f7'})}for(let j=0;j<=2;j++){const v=lo+(hi-lo)*j/2,y=Y(v);svgAdd(svg,'line',{x1:left,y1:y,x2:W-right,y2:y,stroke:'#eef2f7'});svgAdd(svg,'text',{x:left-7,y:y+4,'text-anchor':'end','font-size':10,fill:'#64748b'},Math.abs(v)>20?fmt(v,0):fmt(v,2))}const cols=['#2563eb','#ef4444'];keys.forEach((k,ki)=>svgAdd(svg,'path',{d:pts.map((p,i)=>(i?'L':'M')+X(p.t)+','+Y(p[k])).join(' '),fill:'none',stroke:cols[ki],'stroke-width':2.1,'stroke-linejoin':'round'}));pts.filter(p=>p.edge).forEach(p=>svgAdd(svg,'line',{x1:X(p.t),y1:y0,x2:X(p.t),y2:y0+rh,stroke:'#111827','stroke-width':1,'stroke-dasharray':'3 4',opacity:.65}));svgAdd(svg,'text',{x:8,y:y0+15,'font-size':11,'font-weight':800,fill:'#334155'},s[0]);if(s[1]==='curr'){svgAdd(svg,'text',{x:W-right-5,y:y0+14,'text-anchor':'end','font-size':10,'font-weight':800,fill:'#2563eb'},'iLr');svgAdd(svg,'text',{x:W-right-5,y:y0+28,'text-anchor':'end','font-size':10,'font-weight':800,fill:'#ef4444'},'iLm')}});for(let j=0;j<=4;j++){const x=left+(W-left-right)*j/4;svgAdd(svg,'text',{x,y:H-15,'text-anchor':'middle','font-size':10,fill:'#64748b'},fmt(tmax*j/4,2))}svgAdd(svg,'text',{x:W/2,y:H-2,'text-anchor':'middle','font-size':11,fill:'#334155'},`${zh?'时间':'time'} [µs] · 3 ${zh?'周期':'periods'} · Vo=${fmt(w.Vo,3)} V · residual=${fmt(w.residual,4)}`)}
drawPlaceholder('gainPlot',ui.selectEnvelope);drawPlaceholder('statePlot',ui.selectState);drawPlaceholder('wavePlot',ui.selectWave);
})();
